/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

//! HKDF key derivation for MNCCD flows.
//!
//! TLS certificates and keys are not generated by MNCCD; operators supply PEM
//! material under `tls/` when `[tls].mode = "mtls"`.

/// HKDF `info` labels for flow key material (must stay stable across nodes and releases).
pub(crate) const HKDF_LABEL_PRIMARY_KEY: &str = "primary_key";
pub(crate) const HKDF_LABEL_SECONDARY_KEY: &str = "secondary_key";
pub(crate) const HKDF_LABEL_PRIMARY_IVMASK: &str = "primary_ivmask";
pub(crate) const HKDF_LABEL_SECONDARY_IVMASK: &str = "secondary_ivmask";

/// Derives keys or IV masks using HKDF-SHA256.
pub(crate) fn generate_hkdf_keys_or_iv_masks(
    shared_secret: &[u8],
    secret_name: &str,
    flow_id: u64,
    key_rotation_count: u32,
    output_length: usize,
) -> Result<Vec<u8>, hkdf::InvalidLength> {
    let salt = format!(
        "salt-for-flowid-{}-key-rotation-count-{}",
        flow_id, key_rotation_count
    );
    let salt = salt.as_bytes();
    let info = secret_name.as_bytes();

    let derived_key = generate_hkdf_key(shared_secret, salt, info, output_length)?;
    Ok(derived_key)
}

/// Derives a key of the specified length using HKDF-SHA256 (RFC 5869).
fn generate_hkdf_key(
    shared_secret: &[u8],
    salt: &[u8],
    info: &[u8],
    output_length: usize,
) -> Result<Vec<u8>, hkdf::InvalidLength> {
    use hkdf::Hkdf;
    use sha2::Sha256;

    let hk = Hkdf::<Sha256>::new(Some(salt), shared_secret);
    let mut derived_key = vec![0u8; output_length];
    hk.expand(info, &mut derived_key)?;
    Ok(derived_key)
}

#[cfg(test)]
mod generate_hkdf_key_tests {
    use super::{generate_hkdf_key, HKDF_LABEL_PRIMARY_KEY, HKDF_LABEL_SECONDARY_KEY};

    /// RFC 5869 test case 1 (HKDF-SHA256, 42-byte OKM).
    #[test]
    fn rfc5869_sha256_test_vector() {
        let ikm = [
            0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b,
            0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b,
        ];
        let salt = [
            0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c,
        ];
        let info = [0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9];
        let expected = [
            0x3c, 0xb2, 0x5f, 0x25, 0xfa, 0xac, 0xd5, 0x7a, 0x90, 0x43, 0x4f, 0x64, 0xd0, 0x36,
            0x2f, 0x2a, 0x2d, 0x2d, 0x0a, 0x90, 0xcf, 0x1a, 0x5a, 0x4c, 0x5d, 0xb0, 0x2d, 0x56,
            0xec, 0xc4, 0xc5, 0xbf, 0x34, 0x00, 0x72, 0x08, 0xd5, 0xb8, 0x87, 0x18, 0x58, 0x65,
        ];

        let derived = generate_hkdf_key(&ikm, &salt, &info, expected.len()).expect("hkdf expand");
        assert_eq!(derived, expected);
    }

    #[test]
    fn returns_requested_length() {
        let secret = [0xab; 32];
        let salt = b"salt";
        let info = b"info";

        for len in [1, 12, 32, 64] {
            let derived = generate_hkdf_key(&secret, salt, info, len).expect("hkdf expand");
            assert_eq!(derived.len(), len);
        }
    }

    #[test]
    fn different_info_produces_different_output() {
        let secret = [0xcd; 32];
        let salt = b"same-salt";

        let a = generate_hkdf_key(&secret, salt, HKDF_LABEL_PRIMARY_KEY.as_bytes(), 32)
            .expect("hkdf expand");
        let b = generate_hkdf_key(&secret, salt, HKDF_LABEL_SECONDARY_KEY.as_bytes(), 32)
            .expect("hkdf expand");
        assert_ne!(a, b);
    }

    #[test]
    fn different_salt_produces_different_output() {
        let secret = [0xef; 32];
        let info = HKDF_LABEL_PRIMARY_KEY.as_bytes();

        let a = generate_hkdf_key(&secret, b"salt-a", info, 32).expect("hkdf expand");
        let b = generate_hkdf_key(&secret, b"salt-b", info, 32).expect("hkdf expand");
        assert_ne!(a, b);
    }

    #[test]
    fn matches_flow_salt_format_used_by_generate_hkdf_keys_or_iv_masks() {
        let secret = [0x11; 32];
        let flow_id = 7u64;
        let key_rotation_count = 3u32;
        let salt = format!(
            "salt-for-flowid-{}-key-rotation-count-{}",
            flow_id, key_rotation_count
        );
        let via_helper = super::generate_hkdf_keys_or_iv_masks(
            &secret,
            HKDF_LABEL_PRIMARY_KEY,
            flow_id,
            key_rotation_count,
            32,
        )
        .expect("hkdf expand");
        let via_direct = generate_hkdf_key(
            &secret,
            salt.as_bytes(),
            HKDF_LABEL_PRIMARY_KEY.as_bytes(),
            32,
        )
        .expect("hkdf expand");
        assert_eq!(via_helper, via_direct);
    }
}
